import type { Metadata } from "next";
import "./globals.css";
import { Inter, Sarpanch } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const sarpach = Sarpanch({
  subsets: ["latin"],
  variable: "--font-sarpanch",
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${sarpach.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
